// Flaggr Flag Definition Schema
// Protocol Buffers v3
//
// This schema defines the wire format for feature flag configurations.
// Used for efficient serialization in cache, gRPC streaming, and file storage.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flags.proto

package flaggrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Flag type enumeration
type FlagType int32

const (
	FlagType_FLAG_TYPE_UNSPECIFIED FlagType = 0
	FlagType_FLAG_TYPE_BOOLEAN     FlagType = 1
	FlagType_FLAG_TYPE_STRING      FlagType = 2
	FlagType_FLAG_TYPE_NUMBER      FlagType = 3
	FlagType_FLAG_TYPE_OBJECT      FlagType = 4
)

// Enum value maps for FlagType.
var (
	FlagType_name = map[int32]string{
		0: "FLAG_TYPE_UNSPECIFIED",
		1: "FLAG_TYPE_BOOLEAN",
		2: "FLAG_TYPE_STRING",
		3: "FLAG_TYPE_NUMBER",
		4: "FLAG_TYPE_OBJECT",
	}
	FlagType_value = map[string]int32{
		"FLAG_TYPE_UNSPECIFIED": 0,
		"FLAG_TYPE_BOOLEAN":     1,
		"FLAG_TYPE_STRING":      2,
		"FLAG_TYPE_NUMBER":      3,
		"FLAG_TYPE_OBJECT":      4,
	}
)

func (x FlagType) Enum() *FlagType {
	p := new(FlagType)
	*p = x
	return p
}

func (x FlagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagType) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[0].Descriptor()
}

func (FlagType) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[0]
}

func (x FlagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagType.Descriptor instead.
func (FlagType) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{0}
}

// Environment enumeration
type Environment int32

const (
	Environment_ENVIRONMENT_UNSPECIFIED Environment = 0
	Environment_ENVIRONMENT_DEVELOPMENT Environment = 1
	Environment_ENVIRONMENT_STAGING     Environment = 2
	Environment_ENVIRONMENT_PRODUCTION  Environment = 3
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "ENVIRONMENT_UNSPECIFIED",
		1: "ENVIRONMENT_DEVELOPMENT",
		2: "ENVIRONMENT_STAGING",
		3: "ENVIRONMENT_PRODUCTION",
	}
	Environment_value = map[string]int32{
		"ENVIRONMENT_UNSPECIFIED": 0,
		"ENVIRONMENT_DEVELOPMENT": 1,
		"ENVIRONMENT_STAGING":     2,
		"ENVIRONMENT_PRODUCTION":  3,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[1].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[1]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{1}
}

// Condition operator for targeting rules
type ConditionOperator int32

const (
	ConditionOperator_CONDITION_OPERATOR_UNSPECIFIED           ConditionOperator = 0
	ConditionOperator_CONDITION_OPERATOR_EQUALS                ConditionOperator = 1
	ConditionOperator_CONDITION_OPERATOR_NOT_EQUALS            ConditionOperator = 2
	ConditionOperator_CONDITION_OPERATOR_IN                    ConditionOperator = 3
	ConditionOperator_CONDITION_OPERATOR_NOT_IN                ConditionOperator = 4
	ConditionOperator_CONDITION_OPERATOR_CONTAINS              ConditionOperator = 5
	ConditionOperator_CONDITION_OPERATOR_STARTS_WITH           ConditionOperator = 6
	ConditionOperator_CONDITION_OPERATOR_ENDS_WITH             ConditionOperator = 7
	ConditionOperator_CONDITION_OPERATOR_GREATER_THAN          ConditionOperator = 8
	ConditionOperator_CONDITION_OPERATOR_LESS_THAN             ConditionOperator = 9
	ConditionOperator_CONDITION_OPERATOR_EXISTS                ConditionOperator = 10
	ConditionOperator_CONDITION_OPERATOR_NOT_EXISTS            ConditionOperator = 11
	ConditionOperator_CONDITION_OPERATOR_REGEX                 ConditionOperator = 12
	ConditionOperator_CONDITION_OPERATOR_GREATER_THAN_OR_EQUAL ConditionOperator = 13
	ConditionOperator_CONDITION_OPERATOR_LESS_THAN_OR_EQUAL    ConditionOperator = 14
	ConditionOperator_CONDITION_OPERATOR_BEFORE                ConditionOperator = 15
	ConditionOperator_CONDITION_OPERATOR_AFTER                 ConditionOperator = 16
	ConditionOperator_CONDITION_OPERATOR_IN_COHORT             ConditionOperator = 17
	ConditionOperator_CONDITION_OPERATOR_NOT_IN_COHORT         ConditionOperator = 18
)

// Enum value maps for ConditionOperator.
var (
	ConditionOperator_name = map[int32]string{
		0:  "CONDITION_OPERATOR_UNSPECIFIED",
		1:  "CONDITION_OPERATOR_EQUALS",
		2:  "CONDITION_OPERATOR_NOT_EQUALS",
		3:  "CONDITION_OPERATOR_IN",
		4:  "CONDITION_OPERATOR_NOT_IN",
		5:  "CONDITION_OPERATOR_CONTAINS",
		6:  "CONDITION_OPERATOR_STARTS_WITH",
		7:  "CONDITION_OPERATOR_ENDS_WITH",
		8:  "CONDITION_OPERATOR_GREATER_THAN",
		9:  "CONDITION_OPERATOR_LESS_THAN",
		10: "CONDITION_OPERATOR_EXISTS",
		11: "CONDITION_OPERATOR_NOT_EXISTS",
		12: "CONDITION_OPERATOR_REGEX",
		13: "CONDITION_OPERATOR_GREATER_THAN_OR_EQUAL",
		14: "CONDITION_OPERATOR_LESS_THAN_OR_EQUAL",
		15: "CONDITION_OPERATOR_BEFORE",
		16: "CONDITION_OPERATOR_AFTER",
		17: "CONDITION_OPERATOR_IN_COHORT",
		18: "CONDITION_OPERATOR_NOT_IN_COHORT",
	}
	ConditionOperator_value = map[string]int32{
		"CONDITION_OPERATOR_UNSPECIFIED":           0,
		"CONDITION_OPERATOR_EQUALS":                1,
		"CONDITION_OPERATOR_NOT_EQUALS":            2,
		"CONDITION_OPERATOR_IN":                    3,
		"CONDITION_OPERATOR_NOT_IN":                4,
		"CONDITION_OPERATOR_CONTAINS":              5,
		"CONDITION_OPERATOR_STARTS_WITH":           6,
		"CONDITION_OPERATOR_ENDS_WITH":             7,
		"CONDITION_OPERATOR_GREATER_THAN":          8,
		"CONDITION_OPERATOR_LESS_THAN":             9,
		"CONDITION_OPERATOR_EXISTS":                10,
		"CONDITION_OPERATOR_NOT_EXISTS":            11,
		"CONDITION_OPERATOR_REGEX":                 12,
		"CONDITION_OPERATOR_GREATER_THAN_OR_EQUAL": 13,
		"CONDITION_OPERATOR_LESS_THAN_OR_EQUAL":    14,
		"CONDITION_OPERATOR_BEFORE":                15,
		"CONDITION_OPERATOR_AFTER":                 16,
		"CONDITION_OPERATOR_IN_COHORT":             17,
		"CONDITION_OPERATOR_NOT_IN_COHORT":         18,
	}
)

func (x ConditionOperator) Enum() *ConditionOperator {
	p := new(ConditionOperator)
	*p = x
	return p
}

func (x ConditionOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[2].Descriptor()
}

func (ConditionOperator) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[2]
}

func (x ConditionOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionOperator.Descriptor instead.
func (ConditionOperator) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{2}
}

// Logical operator for combining conditions
type LogicalOperator int32

const (
	LogicalOperator_LOGICAL_OPERATOR_UNSPECIFIED LogicalOperator = 0
	LogicalOperator_LOGICAL_OPERATOR_AND         LogicalOperator = 1
	LogicalOperator_LOGICAL_OPERATOR_OR          LogicalOperator = 2
)

// Enum value maps for LogicalOperator.
var (
	LogicalOperator_name = map[int32]string{
		0: "LOGICAL_OPERATOR_UNSPECIFIED",
		1: "LOGICAL_OPERATOR_AND",
		2: "LOGICAL_OPERATOR_OR",
	}
	LogicalOperator_value = map[string]int32{
		"LOGICAL_OPERATOR_UNSPECIFIED": 0,
		"LOGICAL_OPERATOR_AND":         1,
		"LOGICAL_OPERATOR_OR":          2,
	}
)

func (x LogicalOperator) Enum() *LogicalOperator {
	p := new(LogicalOperator)
	*p = x
	return p
}

func (x LogicalOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_flags_proto_enumTypes[3].Descriptor()
}

func (LogicalOperator) Type() protoreflect.EnumType {
	return &file_flags_proto_enumTypes[3]
}

func (x LogicalOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalOperator.Descriptor instead.
func (LogicalOperator) EnumDescriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{3}
}

// Generic value that can hold different types
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_BoolValue
	//	*Value_StringValue
	//	*Value_NumberValue
	//	*Value_JsonValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_flags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_JsonValue struct {
	JsonValue string `protobuf:"bytes,4,opt,name=json_value,json=jsonValue,proto3,oneof"` // Serialized JSON for object types
}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_NumberValue) isValue_Kind() {}

func (*Value_JsonValue) isValue_Kind() {}

// Array of values for 'in' and 'not_in' operators
type ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueList) Reset() {
	*x = ValueList{}
	mi := &file_flags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueList) ProtoMessage() {}

func (x *ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueList.ProtoReflect.Descriptor instead.
func (*ValueList) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{1}
}

func (x *ValueList) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Condition for targeting rules
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Property name to check in evaluation context
	Property string `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	// Operator to use for comparison
	Operator ConditionOperator `protobuf:"varint,2,opt,name=operator,proto3,enum=flaggr.v1.ConditionOperator" json:"operator,omitempty"`
	// Value to compare against
	//
	// Types that are valid to be assigned to CompareValue:
	//
	//	*Condition_SingleValue
	//	*Condition_ValueList
	CompareValue isCondition_CompareValue `protobuf_oneof:"compare_value"`
	// Cohort identifier for cohort membership operators.
	CohortId      string `protobuf:"bytes,5,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_flags_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{2}
}

func (x *Condition) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *Condition) GetOperator() ConditionOperator {
	if x != nil {
		return x.Operator
	}
	return ConditionOperator_CONDITION_OPERATOR_UNSPECIFIED
}

func (x *Condition) GetCompareValue() isCondition_CompareValue {
	if x != nil {
		return x.CompareValue
	}
	return nil
}

func (x *Condition) GetSingleValue() *Value {
	if x != nil {
		if x, ok := x.CompareValue.(*Condition_SingleValue); ok {
			return x.SingleValue
		}
	}
	return nil
}

func (x *Condition) GetValueList() *ValueList {
	if x != nil {
		if x, ok := x.CompareValue.(*Condition_ValueList); ok {
			return x.ValueList
		}
	}
	return nil
}

func (x *Condition) GetCohortId() string {
	if x != nil {
		return x.CohortId
	}
	return ""
}

type isCondition_CompareValue interface {
	isCondition_CompareValue()
}

type Condition_SingleValue struct {
	SingleValue *Value `protobuf:"bytes,3,opt,name=single_value,json=singleValue,proto3,oneof"`
}

type Condition_ValueList struct {
	ValueList *ValueList `protobuf:"bytes,4,opt,name=value_list,json=valueList,proto3,oneof"`
}

func (*Condition_SingleValue) isCondition_CompareValue() {}

func (*Condition_ValueList) isCondition_CompareValue() {}

// Group of conditions combined with AND logic within the group
type ConditionGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Conditions within this group (AND logic)
	Conditions    []*Condition `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionGroup) Reset() {
	*x = ConditionGroup{}
	mi := &file_flags_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionGroup) ProtoMessage() {}

func (x *ConditionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionGroup.ProtoReflect.Descriptor instead.
func (*ConditionGroup) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{3}
}

func (x *ConditionGroup) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// Targeting rule for conditional flag evaluation
type TargetingRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the rule
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// List of conditions that must be satisfied (flat, combined by condition_operator)
	Conditions []*Condition `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// How to combine conditions (default: AND)
	ConditionOperator LogicalOperator `protobuf:"varint,3,opt,name=condition_operator,json=conditionOperator,proto3,enum=flaggr.v1.LogicalOperator" json:"condition_operator,omitempty"`
	// Variant to serve if rule matches
	Variant string `protobuf:"bytes,4,opt,name=variant,proto3" json:"variant,omitempty"`
	// Direct value to serve if rule matches (alternative to variant)
	Value *Value `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// Condition groups for complex OR logic (groups combined with group_operator)
	Groups []*ConditionGroup `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	// How to combine groups (default: OR - any group matching triggers the rule)
	GroupOperator LogicalOperator `protobuf:"varint,7,opt,name=group_operator,json=groupOperator,proto3,enum=flaggr.v1.LogicalOperator" json:"group_operator,omitempty"`
	// Gradual rollout percentage (0-100). When set, only this percentage of
	// users (determined by consistent hashing on targetingKey) will match.
	RolloutPercentage uint32 `protobuf:"varint,8,opt,name=rollout_percentage,json=rolloutPercentage,proto3" json:"rollout_percentage,omitempty"`
	// Optional time window and recurrence for this rule.
	Schedule *RuleSchedule `protobuf:"bytes,9,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// Distinguishes an explicit 0% rollout from an omitted rollout while
	// preserving field 8's original cardinality for existing clients.
	RolloutPercentageSet bool `protobuf:"varint,10,opt,name=rollout_percentage_set,json=rolloutPercentageSet,proto3" json:"rollout_percentage_set,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TargetingRule) Reset() {
	*x = TargetingRule{}
	mi := &file_flags_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetingRule) ProtoMessage() {}

func (x *TargetingRule) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetingRule.ProtoReflect.Descriptor instead.
func (*TargetingRule) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{4}
}

func (x *TargetingRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TargetingRule) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *TargetingRule) GetConditionOperator() LogicalOperator {
	if x != nil {
		return x.ConditionOperator
	}
	return LogicalOperator_LOGICAL_OPERATOR_UNSPECIFIED
}

func (x *TargetingRule) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *TargetingRule) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TargetingRule) GetGroups() []*ConditionGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *TargetingRule) GetGroupOperator() LogicalOperator {
	if x != nil {
		return x.GroupOperator
	}
	return LogicalOperator_LOGICAL_OPERATOR_UNSPECIFIED
}

func (x *TargetingRule) GetRolloutPercentage() uint32 {
	if x != nil {
		return x.RolloutPercentage
	}
	return 0
}

func (x *TargetingRule) GetSchedule() *RuleSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *TargetingRule) GetRolloutPercentageSet() bool {
	if x != nil {
		return x.RolloutPercentageSet
	}
	return false
}

type RuleSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Recurrence    *ScheduleRecurrence    `protobuf:"bytes,3,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleSchedule) Reset() {
	*x = RuleSchedule{}
	mi := &file_flags_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSchedule) ProtoMessage() {}

func (x *RuleSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSchedule.ProtoReflect.Descriptor instead.
func (*RuleSchedule) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{5}
}

func (x *RuleSchedule) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *RuleSchedule) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *RuleSchedule) GetRecurrence() *ScheduleRecurrence {
	if x != nil {
		return x.Recurrence
	}
	return nil
}

type ScheduleRecurrence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DaysOfWeek    []int32                `protobuf:"varint,2,rep,packed,name=days_of_week,json=daysOfWeek,proto3" json:"days_of_week,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleRecurrence) Reset() {
	*x = ScheduleRecurrence{}
	mi := &file_flags_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleRecurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleRecurrence) ProtoMessage() {}

func (x *ScheduleRecurrence) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleRecurrence.ProtoReflect.Descriptor instead.
func (*ScheduleRecurrence) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{6}
}

func (x *ScheduleRecurrence) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScheduleRecurrence) GetDaysOfWeek() []int32 {
	if x != nil {
		return x.DaysOfWeek
	}
	return nil
}

func (x *ScheduleRecurrence) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleRecurrence) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// Variant definition for percentage-based rollouts
type Variant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Variant name/identifier
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Value for this variant
	Value *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Weight for percentage-based selection (0-100)
	Weight        uint32 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variant) Reset() {
	*x = Variant{}
	mi := &file_flags_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variant) ProtoMessage() {}

func (x *Variant) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variant.ProtoReflect.Descriptor instead.
func (*Variant) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{7}
}

func (x *Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variant) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Variant) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Override struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Identifiers   []string               `protobuf:"bytes,2,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	Value         *Value                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Override) Reset() {
	*x = Override{}
	mi := &file_flags_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Override) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Override) ProtoMessage() {}

func (x *Override) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Override.ProtoReflect.Descriptor instead.
func (*Override) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{8}
}

func (x *Override) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Override) GetIdentifiers() []string {
	if x != nil {
		return x.Identifiers
	}
	return nil
}

func (x *Override) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Override) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type Prerequisite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlagKey       string                 `protobuf:"bytes,1,opt,name=flag_key,json=flagKey,proto3" json:"flag_key,omitempty"`
	ExpectedValue *Value                 `protobuf:"bytes,2,opt,name=expected_value,json=expectedValue,proto3" json:"expected_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prerequisite) Reset() {
	*x = Prerequisite{}
	mi := &file_flags_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prerequisite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prerequisite) ProtoMessage() {}

func (x *Prerequisite) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prerequisite.ProtoReflect.Descriptor instead.
func (*Prerequisite) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{9}
}

func (x *Prerequisite) GetFlagKey() string {
	if x != nil {
		return x.FlagKey
	}
	return ""
}

func (x *Prerequisite) GetExpectedValue() *Value {
	if x != nil {
		return x.ExpectedValue
	}
	return nil
}

// Complete feature flag definition
type Flag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique flag key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Human-readable name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Flag value type
	Type FlagType `protobuf:"varint,4,opt,name=type,proto3,enum=flaggr.v1.FlagType" json:"type,omitempty"`
	// Whether the flag is enabled
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Default value when no rules match
	DefaultValue *Value `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// Project this flag belongs to
	ProjectId string `protobuf:"bytes,7,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Service this flag belongs to
	ServiceId string `protobuf:"bytes,8,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Environment (development, staging, production)
	Environment Environment `protobuf:"varint,9,opt,name=environment,proto3,enum=flaggr.v1.Environment" json:"environment,omitempty"`
	// Tags for organization
	Tags []string `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	// Targeting rules evaluated in order
	TargetingRules []*TargetingRule `protobuf:"bytes,11,rep,name=targeting_rules,json=targetingRules,proto3" json:"targeting_rules,omitempty"`
	// Variants for percentage-based rollouts
	Variants []*Variant `protobuf:"bytes,12,rep,name=variants,proto3" json:"variants,omitempty"`
	// Timestamps
	CreatedAt string `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// User IDs for audit
	CreatedBy string `protobuf:"bytes,15,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy string `protobuf:"bytes,16,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// Version for optimistic locking
	Version uint64 `protobuf:"varint,17,opt,name=version,proto3" json:"version,omitempty"`
	// Identity-specific value overrides.
	Overrides []*Override `protobuf:"bytes,18,rep,name=overrides,proto3" json:"overrides,omitempty"`
	// Flag dependencies required by local evaluators.
	Prerequisites []*Prerequisite `protobuf:"bytes,19,rep,name=prerequisites,proto3" json:"prerequisites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_flags_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{10}
}

func (x *Flag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetType() FlagType {
	if x != nil {
		return x.Type
	}
	return FlagType_FLAG_TYPE_UNSPECIFIED
}

func (x *Flag) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Flag) GetDefaultValue() *Value {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

func (x *Flag) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Flag) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Flag) GetEnvironment() Environment {
	if x != nil {
		return x.Environment
	}
	return Environment_ENVIRONMENT_UNSPECIFIED
}

func (x *Flag) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Flag) GetTargetingRules() []*TargetingRule {
	if x != nil {
		return x.TargetingRules
	}
	return nil
}

func (x *Flag) GetVariants() []*Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *Flag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Flag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Flag) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Flag) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Flag) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Flag) GetOverrides() []*Override {
	if x != nil {
		return x.Overrides
	}
	return nil
}

func (x *Flag) GetPrerequisites() []*Prerequisite {
	if x != nil {
		return x.Prerequisites
	}
	return nil
}

// Collection of flags for bulk operations
type FlagConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of flag key to flag definition
	Flags map[string]*Flag `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Configuration version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// When this configuration was generated
	GeneratedAt string `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	// Service ID for scoped configurations
	ServiceId string `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Project ID for scoped configurations
	ProjectId     string `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagConfiguration) Reset() {
	*x = FlagConfiguration{}
	mi := &file_flags_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagConfiguration) ProtoMessage() {}

func (x *FlagConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagConfiguration.ProtoReflect.Descriptor instead.
func (*FlagConfiguration) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{11}
}

func (x *FlagConfiguration) GetFlags() map[string]*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *FlagConfiguration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FlagConfiguration) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

func (x *FlagConfiguration) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *FlagConfiguration) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

// Service definition
type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_flags_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{12}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Service) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Service) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Service) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// Project definition
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_flags_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_flags_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_flags_proto_rawDescGZIP(), []int{13}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Project) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_flags_proto protoreflect.FileDescriptor

const file_flags_proto_rawDesc = "" +
	"\n" +
	"\vflags.proto\x12\tflaggr.v1\"\x9b\x01\n" +
	"\x05Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x03 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\x04 \x01(\tH\x00R\tjsonValueB\x06\n" +
	"\x04kind\"5\n" +
	"\tValueList\x12(\n" +
	"\x06values\x18\x01 \x03(\v2\x10.flaggr.v1.ValueR\x06values\"\xfd\x01\n" +
	"\tCondition\x12\x1a\n" +
	"\bproperty\x18\x01 \x01(\tR\bproperty\x128\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1c.flaggr.v1.ConditionOperatorR\boperator\x125\n" +
	"\fsingle_value\x18\x03 \x01(\v2\x10.flaggr.v1.ValueH\x00R\vsingleValue\x125\n" +
	"\n" +
	"value_list\x18\x04 \x01(\v2\x14.flaggr.v1.ValueListH\x00R\tvalueList\x12\x1b\n" +
	"\tcohort_id\x18\x05 \x01(\tR\bcohortIdB\x0f\n" +
	"\rcompare_value\"F\n" +
	"\x0eConditionGroup\x124\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x14.flaggr.v1.ConditionR\n" +
	"conditions\"\xf2\x03\n" +
	"\rTargetingRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2\x14.flaggr.v1.ConditionR\n" +
	"conditions\x12I\n" +
	"\x12condition_operator\x18\x03 \x01(\x0e2\x1a.flaggr.v1.LogicalOperatorR\x11conditionOperator\x12\x18\n" +
	"\avariant\x18\x04 \x01(\tR\avariant\x12&\n" +
	"\x05value\x18\x05 \x01(\v2\x10.flaggr.v1.ValueR\x05value\x121\n" +
	"\x06groups\x18\x06 \x03(\v2\x19.flaggr.v1.ConditionGroupR\x06groups\x12A\n" +
	"\x0egroup_operator\x18\a \x01(\x0e2\x1a.flaggr.v1.LogicalOperatorR\rgroupOperator\x12-\n" +
	"\x12rollout_percentage\x18\b \x01(\rR\x11rolloutPercentage\x123\n" +
	"\bschedule\x18\t \x01(\v2\x17.flaggr.v1.RuleScheduleR\bschedule\x124\n" +
	"\x16rollout_percentage_set\x18\n" +
	" \x01(\bR\x14rolloutPercentageSet\"\x87\x01\n" +
	"\fRuleSchedule\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12=\n" +
	"\n" +
	"recurrence\x18\x03 \x01(\v2\x1d.flaggr.v1.ScheduleRecurrenceR\n" +
	"recurrence\"\x84\x01\n" +
	"\x12ScheduleRecurrence\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\fdays_of_week\x18\x02 \x03(\x05R\n" +
	"daysOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\"]\n" +
	"\aVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.flaggr.v1.ValueR\x05value\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\"\x84\x01\n" +
	"\bOverride\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\videntifiers\x18\x02 \x03(\tR\videntifiers\x12&\n" +
	"\x05value\x18\x03 \x01(\v2\x10.flaggr.v1.ValueR\x05value\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"b\n" +
	"\fPrerequisite\x12\x19\n" +
	"\bflag_key\x18\x01 \x01(\tR\aflagKey\x127\n" +
	"\x0eexpected_value\x18\x02 \x01(\v2\x10.flaggr.v1.ValueR\rexpectedValue\"\xcf\x05\n" +
	"\x04Flag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.flaggr.v1.FlagTypeR\x04type\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x125\n" +
	"\rdefault_value\x18\x06 \x01(\v2\x10.flaggr.v1.ValueR\fdefaultValue\x12\x1d\n" +
	"\n" +
	"project_id\x18\a \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"service_id\x18\b \x01(\tR\tserviceId\x128\n" +
	"\venvironment\x18\t \x01(\x0e2\x16.flaggr.v1.EnvironmentR\venvironment\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12A\n" +
	"\x0ftargeting_rules\x18\v \x03(\v2\x18.flaggr.v1.TargetingRuleR\x0etargetingRules\x12.\n" +
	"\bvariants\x18\f \x03(\v2\x12.flaggr.v1.VariantR\bvariants\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x0f \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x10 \x01(\tR\tupdatedBy\x12\x18\n" +
	"\aversion\x18\x11 \x01(\x04R\aversion\x121\n" +
	"\toverrides\x18\x12 \x03(\v2\x13.flaggr.v1.OverrideR\toverrides\x12=\n" +
	"\rprerequisites\x18\x13 \x03(\v2\x17.flaggr.v1.PrerequisiteR\rprerequisites\"\x98\x02\n" +
	"\x11FlagConfiguration\x12=\n" +
	"\x05flags\x18\x01 \x03(\v2'.flaggr.v1.FlagConfiguration.FlagsEntryR\x05flags\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12!\n" +
	"\fgenerated_at\x18\x03 \x01(\tR\vgeneratedAt\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x1aI\n" +
	"\n" +
	"FlagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.flaggr.v1.FlagR\x05value:\x028\x01\"\xdf\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\"\xc0\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy*~\n" +
	"\bFlagType\x12\x19\n" +
	"\x15FLAG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FLAG_TYPE_BOOLEAN\x10\x01\x12\x14\n" +
	"\x10FLAG_TYPE_STRING\x10\x02\x12\x14\n" +
	"\x10FLAG_TYPE_NUMBER\x10\x03\x12\x14\n" +
	"\x10FLAG_TYPE_OBJECT\x10\x04*|\n" +
	"\vEnvironment\x12\x1b\n" +
	"\x17ENVIRONMENT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ENVIRONMENT_DEVELOPMENT\x10\x01\x12\x17\n" +
	"\x13ENVIRONMENT_STAGING\x10\x02\x12\x1a\n" +
	"\x16ENVIRONMENT_PRODUCTION\x10\x03*\x9f\x05\n" +
	"\x11ConditionOperator\x12\"\n" +
	"\x1eCONDITION_OPERATOR_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CONDITION_OPERATOR_EQUALS\x10\x01\x12!\n" +
	"\x1dCONDITION_OPERATOR_NOT_EQUALS\x10\x02\x12\x19\n" +
	"\x15CONDITION_OPERATOR_IN\x10\x03\x12\x1d\n" +
	"\x19CONDITION_OPERATOR_NOT_IN\x10\x04\x12\x1f\n" +
	"\x1bCONDITION_OPERATOR_CONTAINS\x10\x05\x12\"\n" +
	"\x1eCONDITION_OPERATOR_STARTS_WITH\x10\x06\x12 \n" +
	"\x1cCONDITION_OPERATOR_ENDS_WITH\x10\a\x12#\n" +
	"\x1fCONDITION_OPERATOR_GREATER_THAN\x10\b\x12 \n" +
	"\x1cCONDITION_OPERATOR_LESS_THAN\x10\t\x12\x1d\n" +
	"\x19CONDITION_OPERATOR_EXISTS\x10\n" +
	"\x12!\n" +
	"\x1dCONDITION_OPERATOR_NOT_EXISTS\x10\v\x12\x1c\n" +
	"\x18CONDITION_OPERATOR_REGEX\x10\f\x12,\n" +
	"(CONDITION_OPERATOR_GREATER_THAN_OR_EQUAL\x10\r\x12)\n" +
	"%CONDITION_OPERATOR_LESS_THAN_OR_EQUAL\x10\x0e\x12\x1d\n" +
	"\x19CONDITION_OPERATOR_BEFORE\x10\x0f\x12\x1c\n" +
	"\x18CONDITION_OPERATOR_AFTER\x10\x10\x12 \n" +
	"\x1cCONDITION_OPERATOR_IN_COHORT\x10\x11\x12$\n" +
	" CONDITION_OPERATOR_NOT_IN_COHORT\x10\x12*f\n" +
	"\x0fLogicalOperator\x12 \n" +
	"\x1cLOGICAL_OPERATOR_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LOGICAL_OPERATOR_AND\x10\x01\x12\x17\n" +
	"\x13LOGICAL_OPERATOR_OR\x10\x02BK\n" +
	"\x13dev.flaggr.proto.v1P\x01Z2github.com/flaggr-dev/flaggr-cli/internal/flaggrv1b\x06proto3"

var (
	file_flags_proto_rawDescOnce sync.Once
	file_flags_proto_rawDescData []byte
)

func file_flags_proto_rawDescGZIP() []byte {
	file_flags_proto_rawDescOnce.Do(func() {
		file_flags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flags_proto_rawDesc), len(file_flags_proto_rawDesc)))
	})
	return file_flags_proto_rawDescData
}

var file_flags_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_flags_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_flags_proto_goTypes = []any{
	(FlagType)(0),              // 0: flaggr.v1.FlagType
	(Environment)(0),           // 1: flaggr.v1.Environment
	(ConditionOperator)(0),     // 2: flaggr.v1.ConditionOperator
	(LogicalOperator)(0),       // 3: flaggr.v1.LogicalOperator
	(*Value)(nil),              // 4: flaggr.v1.Value
	(*ValueList)(nil),          // 5: flaggr.v1.ValueList
	(*Condition)(nil),          // 6: flaggr.v1.Condition
	(*ConditionGroup)(nil),     // 7: flaggr.v1.ConditionGroup
	(*TargetingRule)(nil),      // 8: flaggr.v1.TargetingRule
	(*RuleSchedule)(nil),       // 9: flaggr.v1.RuleSchedule
	(*ScheduleRecurrence)(nil), // 10: flaggr.v1.ScheduleRecurrence
	(*Variant)(nil),            // 11: flaggr.v1.Variant
	(*Override)(nil),           // 12: flaggr.v1.Override
	(*Prerequisite)(nil),       // 13: flaggr.v1.Prerequisite
	(*Flag)(nil),               // 14: flaggr.v1.Flag
	(*FlagConfiguration)(nil),  // 15: flaggr.v1.FlagConfiguration
	(*Service)(nil),            // 16: flaggr.v1.Service
	(*Project)(nil),            // 17: flaggr.v1.Project
	nil,                        // 18: flaggr.v1.FlagConfiguration.FlagsEntry
}
var file_flags_proto_depIdxs = []int32{
	4,  // 0: flaggr.v1.ValueList.values:type_name -> flaggr.v1.Value
	2,  // 1: flaggr.v1.Condition.operator:type_name -> flaggr.v1.ConditionOperator
	4,  // 2: flaggr.v1.Condition.single_value:type_name -> flaggr.v1.Value
	5,  // 3: flaggr.v1.Condition.value_list:type_name -> flaggr.v1.ValueList
	6,  // 4: flaggr.v1.ConditionGroup.conditions:type_name -> flaggr.v1.Condition
	6,  // 5: flaggr.v1.TargetingRule.conditions:type_name -> flaggr.v1.Condition
	3,  // 6: flaggr.v1.TargetingRule.condition_operator:type_name -> flaggr.v1.LogicalOperator
	4,  // 7: flaggr.v1.TargetingRule.value:type_name -> flaggr.v1.Value
	7,  // 8: flaggr.v1.TargetingRule.groups:type_name -> flaggr.v1.ConditionGroup
	3,  // 9: flaggr.v1.TargetingRule.group_operator:type_name -> flaggr.v1.LogicalOperator
	9,  // 10: flaggr.v1.TargetingRule.schedule:type_name -> flaggr.v1.RuleSchedule
	10, // 11: flaggr.v1.RuleSchedule.recurrence:type_name -> flaggr.v1.ScheduleRecurrence
	4,  // 12: flaggr.v1.Variant.value:type_name -> flaggr.v1.Value
	4,  // 13: flaggr.v1.Override.value:type_name -> flaggr.v1.Value
	4,  // 14: flaggr.v1.Prerequisite.expected_value:type_name -> flaggr.v1.Value
	0,  // 15: flaggr.v1.Flag.type:type_name -> flaggr.v1.FlagType
	4,  // 16: flaggr.v1.Flag.default_value:type_name -> flaggr.v1.Value
	1,  // 17: flaggr.v1.Flag.environment:type_name -> flaggr.v1.Environment
	8,  // 18: flaggr.v1.Flag.targeting_rules:type_name -> flaggr.v1.TargetingRule
	11, // 19: flaggr.v1.Flag.variants:type_name -> flaggr.v1.Variant
	12, // 20: flaggr.v1.Flag.overrides:type_name -> flaggr.v1.Override
	13, // 21: flaggr.v1.Flag.prerequisites:type_name -> flaggr.v1.Prerequisite
	18, // 22: flaggr.v1.FlagConfiguration.flags:type_name -> flaggr.v1.FlagConfiguration.FlagsEntry
	14, // 23: flaggr.v1.FlagConfiguration.FlagsEntry.value:type_name -> flaggr.v1.Flag
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_flags_proto_init() }
func file_flags_proto_init() {
	if File_flags_proto != nil {
		return
	}
	file_flags_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_BoolValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_JsonValue)(nil),
	}
	file_flags_proto_msgTypes[2].OneofWrappers = []any{
		(*Condition_SingleValue)(nil),
		(*Condition_ValueList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flags_proto_rawDesc), len(file_flags_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flags_proto_goTypes,
		DependencyIndexes: file_flags_proto_depIdxs,
		EnumInfos:         file_flags_proto_enumTypes,
		MessageInfos:      file_flags_proto_msgTypes,
	}.Build()
	File_flags_proto = out.File
	file_flags_proto_goTypes = nil
	file_flags_proto_depIdxs = nil
}
