// Flaggr Streaming Protocol Schema
// Protocol Buffers v3
//
// This schema defines the wire format for real-time flag updates via gRPC streaming.
// Supports both server-side and bidirectional streaming patterns.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: streaming.proto

package flaggrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event type for flag updates
type FlagEventType int32

const (
	FlagEventType_FLAG_EVENT_TYPE_UNSPECIFIED FlagEventType = 0
	// Flag was created
	FlagEventType_FLAG_EVENT_TYPE_CREATED FlagEventType = 1
	// Flag was updated
	FlagEventType_FLAG_EVENT_TYPE_UPDATED FlagEventType = 2
	// Flag was deleted
	FlagEventType_FLAG_EVENT_TYPE_DELETED FlagEventType = 3
	// Flag was toggled (enabled/disabled)
	FlagEventType_FLAG_EVENT_TYPE_TOGGLED FlagEventType = 4
	// Full configuration sync
	FlagEventType_FLAG_EVENT_TYPE_SYNC FlagEventType = 5
	// Heartbeat to keep connection alive
	FlagEventType_FLAG_EVENT_TYPE_HEARTBEAT FlagEventType = 6
	// Provider ready signal
	FlagEventType_FLAG_EVENT_TYPE_PROVIDER_READY FlagEventType = 7
	// Provider error signal
	FlagEventType_FLAG_EVENT_TYPE_PROVIDER_ERROR FlagEventType = 8
)

// Enum value maps for FlagEventType.
var (
	FlagEventType_name = map[int32]string{
		0: "FLAG_EVENT_TYPE_UNSPECIFIED",
		1: "FLAG_EVENT_TYPE_CREATED",
		2: "FLAG_EVENT_TYPE_UPDATED",
		3: "FLAG_EVENT_TYPE_DELETED",
		4: "FLAG_EVENT_TYPE_TOGGLED",
		5: "FLAG_EVENT_TYPE_SYNC",
		6: "FLAG_EVENT_TYPE_HEARTBEAT",
		7: "FLAG_EVENT_TYPE_PROVIDER_READY",
		8: "FLAG_EVENT_TYPE_PROVIDER_ERROR",
	}
	FlagEventType_value = map[string]int32{
		"FLAG_EVENT_TYPE_UNSPECIFIED":    0,
		"FLAG_EVENT_TYPE_CREATED":        1,
		"FLAG_EVENT_TYPE_UPDATED":        2,
		"FLAG_EVENT_TYPE_DELETED":        3,
		"FLAG_EVENT_TYPE_TOGGLED":        4,
		"FLAG_EVENT_TYPE_SYNC":           5,
		"FLAG_EVENT_TYPE_HEARTBEAT":      6,
		"FLAG_EVENT_TYPE_PROVIDER_READY": 7,
		"FLAG_EVENT_TYPE_PROVIDER_ERROR": 8,
	}
)

func (x FlagEventType) Enum() *FlagEventType {
	p := new(FlagEventType)
	*p = x
	return p
}

func (x FlagEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_streaming_proto_enumTypes[0].Descriptor()
}

func (FlagEventType) Type() protoreflect.EnumType {
	return &file_streaming_proto_enumTypes[0]
}

func (x FlagEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagEventType.Descriptor instead.
func (FlagEventType) EnumDescriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

// Request to subscribe to flag updates
type StreamFlagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service ID to subscribe to
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Environment to subscribe to
	Environment Environment `protobuf:"varint,2,opt,name=environment,proto3,enum=flaggr.v1.Environment" json:"environment,omitempty"`
	// Specific flag keys to watch (empty = all flags)
	FlagKeys []string `protobuf:"bytes,3,rep,name=flag_keys,json=flagKeys,proto3" json:"flag_keys,omitempty"`
	// Last known configuration version (for delta sync)
	LastKnownVersion string `protobuf:"bytes,4,opt,name=last_known_version,json=lastKnownVersion,proto3" json:"last_known_version,omitempty"`
	// Client identifier for connection tracking
	ClientId string `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// API token for authentication
	ApiToken      string `protobuf:"bytes,6,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFlagsRequest) Reset() {
	*x = StreamFlagsRequest{}
	mi := &file_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFlagsRequest) ProtoMessage() {}

func (x *StreamFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFlagsRequest.ProtoReflect.Descriptor instead.
func (*StreamFlagsRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *StreamFlagsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StreamFlagsRequest) GetEnvironment() Environment {
	if x != nil {
		return x.Environment
	}
	return Environment_ENVIRONMENT_UNSPECIFIED
}

func (x *StreamFlagsRequest) GetFlagKeys() []string {
	if x != nil {
		return x.FlagKeys
	}
	return nil
}

func (x *StreamFlagsRequest) GetLastKnownVersion() string {
	if x != nil {
		return x.LastKnownVersion
	}
	return ""
}

func (x *StreamFlagsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *StreamFlagsRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

// Flag update event sent to clients
type FlagUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type
	EventType FlagEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=flaggr.v1.FlagEventType" json:"event_type,omitempty"`
	// Flag key that was updated
	FlagKey string `protobuf:"bytes,2,opt,name=flag_key,json=flagKey,proto3" json:"flag_key,omitempty"`
	// Full flag configuration (for CREATE/UPDATE events)
	Flag *Flag `protobuf:"bytes,3,opt,name=flag,proto3" json:"flag,omitempty"`
	// Timestamp of the event
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// New configuration version
	ConfigVersion string `protobuf:"bytes,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Error message (for ERROR events)
	ErrorMessage  string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagUpdate) Reset() {
	*x = FlagUpdate{}
	mi := &file_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagUpdate) ProtoMessage() {}

func (x *FlagUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagUpdate.ProtoReflect.Descriptor instead.
func (*FlagUpdate) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *FlagUpdate) GetEventType() FlagEventType {
	if x != nil {
		return x.EventType
	}
	return FlagEventType_FLAG_EVENT_TYPE_UNSPECIFIED
}

func (x *FlagUpdate) GetFlagKey() string {
	if x != nil {
		return x.FlagKey
	}
	return ""
}

func (x *FlagUpdate) GetFlag() *Flag {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *FlagUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *FlagUpdate) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *FlagUpdate) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Full configuration sync message
type ConfigurationSync struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full flag configuration
	Configuration *FlagConfiguration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	// Timestamp of sync
	Timestamp     string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationSync) Reset() {
	*x = ConfigurationSync{}
	mi := &file_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSync) ProtoMessage() {}

func (x *ConfigurationSync) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSync.ProtoReflect.Descriptor instead.
func (*ConfigurationSync) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigurationSync) GetConfiguration() *FlagConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *ConfigurationSync) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// Request for bidirectional sync
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of sync request
	//
	// Types that are valid to be assigned to Request:
	//
	//	*SyncRequest_Subscribe
	//	*SyncRequest_Ack
	//	*SyncRequest_RequestSync
	//	*SyncRequest_Heartbeat
	Request       isSyncRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetRequest() isSyncRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *SyncRequest) GetSubscribe() *StreamFlagsRequest {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *SyncRequest) GetAck() *AcknowledgeUpdate {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *SyncRequest) GetRequestSync() *RequestSync {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_RequestSync); ok {
			return x.RequestSync
		}
	}
	return nil
}

func (x *SyncRequest) GetHeartbeat() *ClientHeartbeat {
	if x != nil {
		if x, ok := x.Request.(*SyncRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isSyncRequest_Request interface {
	isSyncRequest_Request()
}

type SyncRequest_Subscribe struct {
	// Initial subscription request
	Subscribe *StreamFlagsRequest `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type SyncRequest_Ack struct {
	// Acknowledge receipt of update
	Ack *AcknowledgeUpdate `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type SyncRequest_RequestSync struct {
	// Request full configuration sync
	RequestSync *RequestSync `protobuf:"bytes,3,opt,name=request_sync,json=requestSync,proto3,oneof"`
}

type SyncRequest_Heartbeat struct {
	// Client heartbeat
	Heartbeat *ClientHeartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*SyncRequest_Subscribe) isSyncRequest_Request() {}

func (*SyncRequest_Ack) isSyncRequest_Request() {}

func (*SyncRequest_RequestSync) isSyncRequest_Request() {}

func (*SyncRequest_Heartbeat) isSyncRequest_Request() {}

// Acknowledge update receipt
type AcknowledgeUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration version being acknowledged
	ConfigVersion string `protobuf:"bytes,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Flag keys successfully applied
	AppliedFlags  []string `protobuf:"bytes,2,rep,name=applied_flags,json=appliedFlags,proto3" json:"applied_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeUpdate) Reset() {
	*x = AcknowledgeUpdate{}
	mi := &file_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeUpdate) ProtoMessage() {}

func (x *AcknowledgeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeUpdate.ProtoReflect.Descriptor instead.
func (*AcknowledgeUpdate) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *AcknowledgeUpdate) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *AcknowledgeUpdate) GetAppliedFlags() []string {
	if x != nil {
		return x.AppliedFlags
	}
	return nil
}

// Request for full configuration sync
type RequestSync struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last known version (for delta sync)
	LastKnownVersion string `protobuf:"bytes,1,opt,name=last_known_version,json=lastKnownVersion,proto3" json:"last_known_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestSync) Reset() {
	*x = RequestSync{}
	mi := &file_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSync) ProtoMessage() {}

func (x *RequestSync) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSync.ProtoReflect.Descriptor instead.
func (*RequestSync) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *RequestSync) GetLastKnownVersion() string {
	if x != nil {
		return x.LastKnownVersion
	}
	return ""
}

// Client heartbeat message
type ClientHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client timestamp
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Active flag keys in client cache
	CachedFlags   []string `protobuf:"bytes,2,rep,name=cached_flags,json=cachedFlags,proto3" json:"cached_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHeartbeat) Reset() {
	*x = ClientHeartbeat{}
	mi := &file_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHeartbeat) ProtoMessage() {}

func (x *ClientHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHeartbeat.ProtoReflect.Descriptor instead.
func (*ClientHeartbeat) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *ClientHeartbeat) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ClientHeartbeat) GetCachedFlags() []string {
	if x != nil {
		return x.CachedFlags
	}
	return nil
}

// Response for bidirectional sync
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of sync response
	//
	// Types that are valid to be assigned to Response:
	//
	//	*SyncResponse_Update
	//	*SyncResponse_Sync
	//	*SyncResponse_Heartbeat
	//	*SyncResponse_Error
	Response      isSyncResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_streaming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{7}
}

func (x *SyncResponse) GetResponse() isSyncResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SyncResponse) GetUpdate() *FlagUpdate {
	if x != nil {
		if x, ok := x.Response.(*SyncResponse_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *SyncResponse) GetSync() *ConfigurationSync {
	if x != nil {
		if x, ok := x.Response.(*SyncResponse_Sync); ok {
			return x.Sync
		}
	}
	return nil
}

func (x *SyncResponse) GetHeartbeat() *ServerHeartbeat {
	if x != nil {
		if x, ok := x.Response.(*SyncResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *SyncResponse) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Response.(*SyncResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSyncResponse_Response interface {
	isSyncResponse_Response()
}

type SyncResponse_Update struct {
	// Flag update event
	Update *FlagUpdate `protobuf:"bytes,1,opt,name=update,proto3,oneof"`
}

type SyncResponse_Sync struct {
	// Full configuration sync
	Sync *ConfigurationSync `protobuf:"bytes,2,opt,name=sync,proto3,oneof"`
}

type SyncResponse_Heartbeat struct {
	// Server heartbeat
	Heartbeat *ServerHeartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type SyncResponse_Error struct {
	// Error response
	Error *StreamError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SyncResponse_Update) isSyncResponse_Response() {}

func (*SyncResponse_Sync) isSyncResponse_Response() {}

func (*SyncResponse_Heartbeat) isSyncResponse_Response() {}

func (*SyncResponse_Error) isSyncResponse_Response() {}

// Server heartbeat message
type ServerHeartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server timestamp
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Current configuration version
	ConfigVersion string `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Server instance identifier
	ServerId      string `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHeartbeat) Reset() {
	*x = ServerHeartbeat{}
	mi := &file_streaming_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHeartbeat) ProtoMessage() {}

func (x *ServerHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHeartbeat.ProtoReflect.Descriptor instead.
func (*ServerHeartbeat) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{8}
}

func (x *ServerHeartbeat) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ServerHeartbeat) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *ServerHeartbeat) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Stream error message
type StreamError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Error code
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Whether client should reconnect
	ShouldReconnect bool `protobuf:"varint,3,opt,name=should_reconnect,json=shouldReconnect,proto3" json:"should_reconnect,omitempty"`
	// Recommended retry delay in milliseconds
	RetryDelayMs  uint32 `protobuf:"varint,4,opt,name=retry_delay_ms,json=retryDelayMs,proto3" json:"retry_delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_streaming_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{9}
}

func (x *StreamError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamError) GetShouldReconnect() bool {
	if x != nil {
		return x.ShouldReconnect
	}
	return false
}

func (x *StreamError) GetRetryDelayMs() uint32 {
	if x != nil {
		return x.RetryDelayMs
	}
	return 0
}

// Connection metadata for monitoring
type ConnectionMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique connection identifier
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	// Client identifier
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Service ID being watched
	ServiceId string `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Environment being watched
	Environment Environment `protobuf:"varint,4,opt,name=environment,proto3,enum=flaggr.v1.Environment" json:"environment,omitempty"`
	// Connection established timestamp
	ConnectedAt string `protobuf:"bytes,5,opt,name=connected_at,json=connectedAt,proto3" json:"connected_at,omitempty"`
	// Last activity timestamp
	LastActivityAt string `protobuf:"bytes,6,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	// Number of updates sent
	UpdatesSent   uint64 `protobuf:"varint,7,opt,name=updates_sent,json=updatesSent,proto3" json:"updates_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionMetadata) Reset() {
	*x = ConnectionMetadata{}
	mi := &file_streaming_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionMetadata) ProtoMessage() {}

func (x *ConnectionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionMetadata.ProtoReflect.Descriptor instead.
func (*ConnectionMetadata) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectionMetadata) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionMetadata) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectionMetadata) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ConnectionMetadata) GetEnvironment() Environment {
	if x != nil {
		return x.Environment
	}
	return Environment_ENVIRONMENT_UNSPECIFIED
}

func (x *ConnectionMetadata) GetConnectedAt() string {
	if x != nil {
		return x.ConnectedAt
	}
	return ""
}

func (x *ConnectionMetadata) GetLastActivityAt() string {
	if x != nil {
		return x.LastActivityAt
	}
	return ""
}

func (x *ConnectionMetadata) GetUpdatesSent() uint64 {
	if x != nil {
		return x.UpdatesSent
	}
	return 0
}

// Provider metadata for OFREP compatibility
type ProviderMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Provider name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Provider version
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Supported capabilities
	Capabilities  []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderMetadata) Reset() {
	*x = ProviderMetadata{}
	mi := &file_streaming_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderMetadata) ProtoMessage() {}

func (x *ProviderMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderMetadata.ProtoReflect.Descriptor instead.
func (*ProviderMetadata) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderMetadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderMetadata) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Metadata request
type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_streaming_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{12}
}

// Metadata response
type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *ProviderMetadata      `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_streaming_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{13}
}

func (x *GetMetadataResponse) GetProvider() *ProviderMetadata {
	if x != nil {
		return x.Provider
	}
	return nil
}

var File_streaming_proto protoreflect.FileDescriptor

const file_streaming_proto_rawDesc = "" +
	"\n" +
	"\x0fstreaming.proto\x12\tflaggr.v1\x1a\vflags.proto\x1a\x10evaluation.proto\"\xf2\x01\n" +
	"\x12StreamFlagsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x128\n" +
	"\venvironment\x18\x02 \x01(\x0e2\x16.flaggr.v1.EnvironmentR\venvironment\x12\x1b\n" +
	"\tflag_keys\x18\x03 \x03(\tR\bflagKeys\x12,\n" +
	"\x12last_known_version\x18\x04 \x01(\tR\x10lastKnownVersion\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12\x1b\n" +
	"\tapi_token\x18\x06 \x01(\tR\bapiToken\"\xef\x01\n" +
	"\n" +
	"FlagUpdate\x127\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x18.flaggr.v1.FlagEventTypeR\teventType\x12\x19\n" +
	"\bflag_key\x18\x02 \x01(\tR\aflagKey\x12#\n" +
	"\x04flag\x18\x03 \x01(\v2\x0f.flaggr.v1.FlagR\x04flag\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12%\n" +
	"\x0econfig_version\x18\x05 \x01(\tR\rconfigVersion\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"u\n" +
	"\x11ConfigurationSync\x12B\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x1c.flaggr.v1.FlagConfigurationR\rconfiguration\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\x82\x02\n" +
	"\vSyncRequest\x12=\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1d.flaggr.v1.StreamFlagsRequestH\x00R\tsubscribe\x120\n" +
	"\x03ack\x18\x02 \x01(\v2\x1c.flaggr.v1.AcknowledgeUpdateH\x00R\x03ack\x12;\n" +
	"\frequest_sync\x18\x03 \x01(\v2\x16.flaggr.v1.RequestSyncH\x00R\vrequestSync\x12:\n" +
	"\theartbeat\x18\x04 \x01(\v2\x1a.flaggr.v1.ClientHeartbeatH\x00R\theartbeatB\t\n" +
	"\arequest\"_\n" +
	"\x11AcknowledgeUpdate\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\tR\rconfigVersion\x12#\n" +
	"\rapplied_flags\x18\x02 \x03(\tR\fappliedFlags\";\n" +
	"\vRequestSync\x12,\n" +
	"\x12last_known_version\x18\x01 \x01(\tR\x10lastKnownVersion\"R\n" +
	"\x0fClientHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12!\n" +
	"\fcached_flags\x18\x02 \x03(\tR\vcachedFlags\"\xeb\x01\n" +
	"\fSyncResponse\x12/\n" +
	"\x06update\x18\x01 \x01(\v2\x15.flaggr.v1.FlagUpdateH\x00R\x06update\x122\n" +
	"\x04sync\x18\x02 \x01(\v2\x1c.flaggr.v1.ConfigurationSyncH\x00R\x04sync\x12:\n" +
	"\theartbeat\x18\x03 \x01(\v2\x1a.flaggr.v1.ServerHeartbeatH\x00R\theartbeat\x12.\n" +
	"\x05error\x18\x04 \x01(\v2\x16.flaggr.v1.StreamErrorH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"s\n" +
	"\x0fServerHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"\x8c\x01\n" +
	"\vStreamError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10should_reconnect\x18\x03 \x01(\bR\x0fshouldReconnect\x12$\n" +
	"\x0eretry_delay_ms\x18\x04 \x01(\rR\fretryDelayMs\"\x9f\x02\n" +
	"\x12ConnectionMetadata\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x128\n" +
	"\venvironment\x18\x04 \x01(\x0e2\x16.flaggr.v1.EnvironmentR\venvironment\x12!\n" +
	"\fconnected_at\x18\x05 \x01(\tR\vconnectedAt\x12(\n" +
	"\x10last_activity_at\x18\x06 \x01(\tR\x0elastActivityAt\x12!\n" +
	"\fupdates_sent\x18\a \x01(\x04R\vupdatesSent\"d\n" +
	"\x10ProviderMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x14\n" +
	"\x12GetMetadataRequest\"N\n" +
	"\x13GetMetadataResponse\x127\n" +
	"\bprovider\x18\x01 \x01(\v2\x1b.flaggr.v1.ProviderMetadataR\bprovider*\xa5\x02\n" +
	"\rFlagEventType\x12\x1f\n" +
	"\x1bFLAG_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FLAG_EVENT_TYPE_CREATED\x10\x01\x12\x1b\n" +
	"\x17FLAG_EVENT_TYPE_UPDATED\x10\x02\x12\x1b\n" +
	"\x17FLAG_EVENT_TYPE_DELETED\x10\x03\x12\x1b\n" +
	"\x17FLAG_EVENT_TYPE_TOGGLED\x10\x04\x12\x18\n" +
	"\x14FLAG_EVENT_TYPE_SYNC\x10\x05\x12\x1d\n" +
	"\x19FLAG_EVENT_TYPE_HEARTBEAT\x10\x06\x12\"\n" +
	"\x1eFLAG_EVENT_TYPE_PROVIDER_READY\x10\a\x12\"\n" +
	"\x1eFLAG_EVENT_TYPE_PROVIDER_ERROR\x10\b2\xed\x01\n" +
	"\x11FlagStreamService\x12E\n" +
	"\vStreamFlags\x12\x1d.flaggr.v1.StreamFlagsRequest\x1a\x15.flaggr.v1.FlagUpdate0\x01\x12@\n" +
	"\tSyncFlags\x12\x16.flaggr.v1.SyncRequest\x1a\x17.flaggr.v1.SyncResponse(\x010\x01\x12O\n" +
	"\x10GetConfiguration\x12\x1d.flaggr.v1.StreamFlagsRequest\x1a\x1c.flaggr.v1.ConfigurationSyncBK\n" +
	"\x13dev.flaggr.proto.v1P\x01Z2github.com/flaggr-dev/flaggr-cli/internal/flaggrv1b\x06proto3"

var (
	file_streaming_proto_rawDescOnce sync.Once
	file_streaming_proto_rawDescData []byte
)

func file_streaming_proto_rawDescGZIP() []byte {
	file_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)))
	})
	return file_streaming_proto_rawDescData
}

var file_streaming_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_streaming_proto_goTypes = []any{
	(FlagEventType)(0),          // 0: flaggr.v1.FlagEventType
	(*StreamFlagsRequest)(nil),  // 1: flaggr.v1.StreamFlagsRequest
	(*FlagUpdate)(nil),          // 2: flaggr.v1.FlagUpdate
	(*ConfigurationSync)(nil),   // 3: flaggr.v1.ConfigurationSync
	(*SyncRequest)(nil),         // 4: flaggr.v1.SyncRequest
	(*AcknowledgeUpdate)(nil),   // 5: flaggr.v1.AcknowledgeUpdate
	(*RequestSync)(nil),         // 6: flaggr.v1.RequestSync
	(*ClientHeartbeat)(nil),     // 7: flaggr.v1.ClientHeartbeat
	(*SyncResponse)(nil),        // 8: flaggr.v1.SyncResponse
	(*ServerHeartbeat)(nil),     // 9: flaggr.v1.ServerHeartbeat
	(*StreamError)(nil),         // 10: flaggr.v1.StreamError
	(*ConnectionMetadata)(nil),  // 11: flaggr.v1.ConnectionMetadata
	(*ProviderMetadata)(nil),    // 12: flaggr.v1.ProviderMetadata
	(*GetMetadataRequest)(nil),  // 13: flaggr.v1.GetMetadataRequest
	(*GetMetadataResponse)(nil), // 14: flaggr.v1.GetMetadataResponse
	(Environment)(0),            // 15: flaggr.v1.Environment
	(*Flag)(nil),                // 16: flaggr.v1.Flag
	(*FlagConfiguration)(nil),   // 17: flaggr.v1.FlagConfiguration
}
var file_streaming_proto_depIdxs = []int32{
	15, // 0: flaggr.v1.StreamFlagsRequest.environment:type_name -> flaggr.v1.Environment
	0,  // 1: flaggr.v1.FlagUpdate.event_type:type_name -> flaggr.v1.FlagEventType
	16, // 2: flaggr.v1.FlagUpdate.flag:type_name -> flaggr.v1.Flag
	17, // 3: flaggr.v1.ConfigurationSync.configuration:type_name -> flaggr.v1.FlagConfiguration
	1,  // 4: flaggr.v1.SyncRequest.subscribe:type_name -> flaggr.v1.StreamFlagsRequest
	5,  // 5: flaggr.v1.SyncRequest.ack:type_name -> flaggr.v1.AcknowledgeUpdate
	6,  // 6: flaggr.v1.SyncRequest.request_sync:type_name -> flaggr.v1.RequestSync
	7,  // 7: flaggr.v1.SyncRequest.heartbeat:type_name -> flaggr.v1.ClientHeartbeat
	2,  // 8: flaggr.v1.SyncResponse.update:type_name -> flaggr.v1.FlagUpdate
	3,  // 9: flaggr.v1.SyncResponse.sync:type_name -> flaggr.v1.ConfigurationSync
	9,  // 10: flaggr.v1.SyncResponse.heartbeat:type_name -> flaggr.v1.ServerHeartbeat
	10, // 11: flaggr.v1.SyncResponse.error:type_name -> flaggr.v1.StreamError
	15, // 12: flaggr.v1.ConnectionMetadata.environment:type_name -> flaggr.v1.Environment
	12, // 13: flaggr.v1.GetMetadataResponse.provider:type_name -> flaggr.v1.ProviderMetadata
	1,  // 14: flaggr.v1.FlagStreamService.StreamFlags:input_type -> flaggr.v1.StreamFlagsRequest
	4,  // 15: flaggr.v1.FlagStreamService.SyncFlags:input_type -> flaggr.v1.SyncRequest
	1,  // 16: flaggr.v1.FlagStreamService.GetConfiguration:input_type -> flaggr.v1.StreamFlagsRequest
	2,  // 17: flaggr.v1.FlagStreamService.StreamFlags:output_type -> flaggr.v1.FlagUpdate
	8,  // 18: flaggr.v1.FlagStreamService.SyncFlags:output_type -> flaggr.v1.SyncResponse
	3,  // 19: flaggr.v1.FlagStreamService.GetConfiguration:output_type -> flaggr.v1.ConfigurationSync
	17, // [17:20] is the sub-list for method output_type
	14, // [14:17] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_streaming_proto_init() }
func file_streaming_proto_init() {
	if File_streaming_proto != nil {
		return
	}
	file_flags_proto_init()
	file_evaluation_proto_init()
	file_streaming_proto_msgTypes[3].OneofWrappers = []any{
		(*SyncRequest_Subscribe)(nil),
		(*SyncRequest_Ack)(nil),
		(*SyncRequest_RequestSync)(nil),
		(*SyncRequest_Heartbeat)(nil),
	}
	file_streaming_proto_msgTypes[7].OneofWrappers = []any{
		(*SyncResponse_Update)(nil),
		(*SyncResponse_Sync)(nil),
		(*SyncResponse_Heartbeat)(nil),
		(*SyncResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_proto_rawDesc), len(file_streaming_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_proto_depIdxs,
		EnumInfos:         file_streaming_proto_enumTypes,
		MessageInfos:      file_streaming_proto_msgTypes,
	}.Build()
	File_streaming_proto = out.File
	file_streaming_proto_goTypes = nil
	file_streaming_proto_depIdxs = nil
}
