// Flaggr Streaming Protocol Schema
// Protocol Buffers v3
//
// This schema defines the wire format for real-time flag updates via gRPC streaming.
// Supports both server-side and bidirectional streaming patterns.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: streaming.proto

package flaggrv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	flaggrv1 "github.com/flaggr-dev/flaggr-cli/internal/flaggrv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FlagStreamServiceName is the fully-qualified name of the FlagStreamService service.
	FlagStreamServiceName = "flaggr.v1.FlagStreamService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FlagStreamServiceStreamFlagsProcedure is the fully-qualified name of the FlagStreamService's
	// StreamFlags RPC.
	FlagStreamServiceStreamFlagsProcedure = "/flaggr.v1.FlagStreamService/StreamFlags"
	// FlagStreamServiceSyncFlagsProcedure is the fully-qualified name of the FlagStreamService's
	// SyncFlags RPC.
	FlagStreamServiceSyncFlagsProcedure = "/flaggr.v1.FlagStreamService/SyncFlags"
	// FlagStreamServiceGetConfigurationProcedure is the fully-qualified name of the FlagStreamService's
	// GetConfiguration RPC.
	FlagStreamServiceGetConfigurationProcedure = "/flaggr.v1.FlagStreamService/GetConfiguration"
)

// FlagStreamServiceClient is a client for the flaggr.v1.FlagStreamService service.
type FlagStreamServiceClient interface {
	// Server-side streaming: Subscribe to flag updates
	StreamFlags(context.Context, *connect.Request[flaggrv1.StreamFlagsRequest]) (*connect.ServerStreamForClient[flaggrv1.FlagUpdate], error)
	// Bidirectional streaming: Sync flags with acknowledgments
	SyncFlags(context.Context) *connect.BidiStreamForClient[flaggrv1.SyncRequest, flaggrv1.SyncResponse]
	// Get current configuration (unary, for initial load)
	GetConfiguration(context.Context, *connect.Request[flaggrv1.StreamFlagsRequest]) (*connect.Response[flaggrv1.ConfigurationSync], error)
}

// NewFlagStreamServiceClient constructs a client for the flaggr.v1.FlagStreamService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFlagStreamServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FlagStreamServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	flagStreamServiceMethods := flaggrv1.File_streaming_proto.Services().ByName("FlagStreamService").Methods()
	return &flagStreamServiceClient{
		streamFlags: connect.NewClient[flaggrv1.StreamFlagsRequest, flaggrv1.FlagUpdate](
			httpClient,
			baseURL+FlagStreamServiceStreamFlagsProcedure,
			connect.WithSchema(flagStreamServiceMethods.ByName("StreamFlags")),
			connect.WithClientOptions(opts...),
		),
		syncFlags: connect.NewClient[flaggrv1.SyncRequest, flaggrv1.SyncResponse](
			httpClient,
			baseURL+FlagStreamServiceSyncFlagsProcedure,
			connect.WithSchema(flagStreamServiceMethods.ByName("SyncFlags")),
			connect.WithClientOptions(opts...),
		),
		getConfiguration: connect.NewClient[flaggrv1.StreamFlagsRequest, flaggrv1.ConfigurationSync](
			httpClient,
			baseURL+FlagStreamServiceGetConfigurationProcedure,
			connect.WithSchema(flagStreamServiceMethods.ByName("GetConfiguration")),
			connect.WithClientOptions(opts...),
		),
	}
}

// flagStreamServiceClient implements FlagStreamServiceClient.
type flagStreamServiceClient struct {
	streamFlags      *connect.Client[flaggrv1.StreamFlagsRequest, flaggrv1.FlagUpdate]
	syncFlags        *connect.Client[flaggrv1.SyncRequest, flaggrv1.SyncResponse]
	getConfiguration *connect.Client[flaggrv1.StreamFlagsRequest, flaggrv1.ConfigurationSync]
}

// StreamFlags calls flaggr.v1.FlagStreamService.StreamFlags.
func (c *flagStreamServiceClient) StreamFlags(ctx context.Context, req *connect.Request[flaggrv1.StreamFlagsRequest]) (*connect.ServerStreamForClient[flaggrv1.FlagUpdate], error) {
	return c.streamFlags.CallServerStream(ctx, req)
}

// SyncFlags calls flaggr.v1.FlagStreamService.SyncFlags.
func (c *flagStreamServiceClient) SyncFlags(ctx context.Context) *connect.BidiStreamForClient[flaggrv1.SyncRequest, flaggrv1.SyncResponse] {
	return c.syncFlags.CallBidiStream(ctx)
}

// GetConfiguration calls flaggr.v1.FlagStreamService.GetConfiguration.
func (c *flagStreamServiceClient) GetConfiguration(ctx context.Context, req *connect.Request[flaggrv1.StreamFlagsRequest]) (*connect.Response[flaggrv1.ConfigurationSync], error) {
	return c.getConfiguration.CallUnary(ctx, req)
}

// FlagStreamServiceHandler is an implementation of the flaggr.v1.FlagStreamService service.
type FlagStreamServiceHandler interface {
	// Server-side streaming: Subscribe to flag updates
	StreamFlags(context.Context, *connect.Request[flaggrv1.StreamFlagsRequest], *connect.ServerStream[flaggrv1.FlagUpdate]) error
	// Bidirectional streaming: Sync flags with acknowledgments
	SyncFlags(context.Context, *connect.BidiStream[flaggrv1.SyncRequest, flaggrv1.SyncResponse]) error
	// Get current configuration (unary, for initial load)
	GetConfiguration(context.Context, *connect.Request[flaggrv1.StreamFlagsRequest]) (*connect.Response[flaggrv1.ConfigurationSync], error)
}

// NewFlagStreamServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFlagStreamServiceHandler(svc FlagStreamServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	flagStreamServiceMethods := flaggrv1.File_streaming_proto.Services().ByName("FlagStreamService").Methods()
	flagStreamServiceStreamFlagsHandler := connect.NewServerStreamHandler(
		FlagStreamServiceStreamFlagsProcedure,
		svc.StreamFlags,
		connect.WithSchema(flagStreamServiceMethods.ByName("StreamFlags")),
		connect.WithHandlerOptions(opts...),
	)
	flagStreamServiceSyncFlagsHandler := connect.NewBidiStreamHandler(
		FlagStreamServiceSyncFlagsProcedure,
		svc.SyncFlags,
		connect.WithSchema(flagStreamServiceMethods.ByName("SyncFlags")),
		connect.WithHandlerOptions(opts...),
	)
	flagStreamServiceGetConfigurationHandler := connect.NewUnaryHandler(
		FlagStreamServiceGetConfigurationProcedure,
		svc.GetConfiguration,
		connect.WithSchema(flagStreamServiceMethods.ByName("GetConfiguration")),
		connect.WithHandlerOptions(opts...),
	)
	return "/flaggr.v1.FlagStreamService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FlagStreamServiceStreamFlagsProcedure:
			flagStreamServiceStreamFlagsHandler.ServeHTTP(w, r)
		case FlagStreamServiceSyncFlagsProcedure:
			flagStreamServiceSyncFlagsHandler.ServeHTTP(w, r)
		case FlagStreamServiceGetConfigurationProcedure:
			flagStreamServiceGetConfigurationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFlagStreamServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFlagStreamServiceHandler struct{}

func (UnimplementedFlagStreamServiceHandler) StreamFlags(context.Context, *connect.Request[flaggrv1.StreamFlagsRequest], *connect.ServerStream[flaggrv1.FlagUpdate]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("flaggr.v1.FlagStreamService.StreamFlags is not implemented"))
}

func (UnimplementedFlagStreamServiceHandler) SyncFlags(context.Context, *connect.BidiStream[flaggrv1.SyncRequest, flaggrv1.SyncResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("flaggr.v1.FlagStreamService.SyncFlags is not implemented"))
}

func (UnimplementedFlagStreamServiceHandler) GetConfiguration(context.Context, *connect.Request[flaggrv1.StreamFlagsRequest]) (*connect.Response[flaggrv1.ConfigurationSync], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("flaggr.v1.FlagStreamService.GetConfiguration is not implemented"))
}
